#!/usr/bin/env ruby
# frozen_string_literal: true

lib_path = File.expand_path('../lib', __dir__)
$:.unshift(lib_path) if !$:.include?(lib_path)
require 'poke/cli'

Signal.trap('INT') do
  warn("\n#{caller.join("\n")}: interrupted")
  exit(1)
end

begin
  # run default command if the first command is not recognised
  Poke::CLI.start(ARGV)
rescue Poke::CLI::Error => e
  puts "ERROR: #{e.message}"
  exit 1
end
